/**
 * MySQL / MariaDB source (the database you manage in phpMyAdmin).
 *
 * Two ways to use it, both read-only (`SELECT ... LIMIT n`, no SQL is ever
 * generated by the model):
 *
 *   DB_POLICIES_TABLE  a table holding policies. Recognised columns:
 *                      id, title|name, content|text|body|description, category, keywords
 *                      (keywords = comma-separated string or JSON array).
 *   DB_TABLES          comma-separated list of any other tables (products, faq,
 *                      employees, ...). Every row becomes one searchable record
 *                      "col: value | col: value" so the assistant can answer
 *                      questions from your data.
 *
 * Rows are re-read every DB_REFRESH_SECONDS. Use a MySQL user that only has
 * SELECT on the listed tables — everything loaded here can be shown to anyone
 * who can chat with the widget.
 */

const IDENT = /^[A-Za-z0-9_$]+$/;
const LABEL_COLUMNS = ['name', 'title', 'question', 'label', 'subject', 'product', 'sku', 'code'];
const MAX_VALUE = 500;

function ident(name) {
  if (!IDENT.test(name)) throw new Error(`invalid table name: ${name}`);
  return `\`${name}\``;
}

function parseUrl(url) {
  const u = new URL(url);
  if (!/^mysql2?:$/.test(u.protocol)) throw new Error('DB_URL must start with mysql://');
  return {
    host: u.hostname || 'localhost',
    port: u.port ? Number(u.port) : 3306,
    user: decodeURIComponent(u.username),
    password: decodeURIComponent(u.password),
    database: u.pathname.replace(/^\//, ''),
  };
}

function formatValue(v) {
  if (v === null || v === undefined) return null;
  if (Buffer.isBuffer(v)) return null;
  if (v instanceof Date) return Number.isNaN(v.getTime()) ? null : v.toISOString().slice(0, 10);
  if (typeof v === 'object') v = JSON.stringify(v);
  const s = String(v).trim();
  if (!s) return null;
  return s.length > MAX_VALUE ? `${s.slice(0, MAX_VALUE)}…` : s;
}

function pick(row, names) {
  for (const n of names) if (row[n] !== undefined && row[n] !== null) return row[n];
  return undefined;
}

/** Converts a row of a policies table into a policy, or null when it lacks title/content. */
export function policyFromRow(row, table, index) {
  const title = pick(row, ['title', 'name']);
  const content = pick(row, ['content', 'text', 'body', 'description']);
  if (!title || !content) return null;
  let keywords = row.keywords;
  if (typeof keywords === 'string') {
    try {
      const parsed = JSON.parse(keywords);
      keywords = Array.isArray(parsed) ? parsed : keywords.split(',');
    } catch {
      keywords = keywords.split(',');
    }
  }
  return {
    id: `db:${table}:${row.id ?? index}`,
    category: String(row.category ?? 'policy'),
    title: String(title),
    content: String(content),
    keywords: Array.isArray(keywords) ? keywords.map((k) => String(k).trim()).filter(Boolean) : [],
    source: 'db',
  };
}

/** Converts any table row into a searchable record. */
export function recordFromRow(row, table, index) {
  const cols = Object.keys(row);
  const labelCol = cols.find((c) => LABEL_COLUMNS.includes(c.toLowerCase()));
  const label = formatValue(labelCol ? row[labelCol] : null) ?? `#${row.id ?? index + 1}`;
  const parts = [];
  const keywords = [];
  for (const c of cols) {
    const v = formatValue(row[c]);
    if (v === null) continue;
    parts.push(`${c}: ${v}`);
    if (typeof row[c] === 'string' && v.length <= 40 && /[a-z]/i.test(v))
      keywords.push(v.toLowerCase());
  }
  if (parts.length === 0) return null;
  return {
    id: `db:${table}:${row.id ?? index}`,
    category: table,
    title: `${table}: ${label}`.slice(0, 120),
    content: parts.join(' | '),
    keywords: [...new Set([table.toLowerCase(), ...keywords])],
    source: 'db',
  };
}

/**
 * Connects, loads the configured tables and calls `onLoad(policies)` now and on
 * every refresh. Returns `{ refresh, close }`.
 */
export async function createDbSource(
  { url, policiesTable = '', tables = [], maxRows = 500, refreshSeconds = 60 },
  onLoad,
) {
  const mysql = await import('mysql2/promise');
  const pool = mysql.createPool({
    ...parseUrl(url),
    waitForConnections: true,
    connectionLimit: 2,
    dateStrings: false,
  });
  const targets = [
    ...(policiesTable ? [{ table: policiesTable, kind: 'policies' }] : []),
    ...tables.filter(Boolean).map((table) => ({ table, kind: 'records' })),
  ];
  for (const t of targets) ident(t.table); // validate names up front
  if (targets.length === 0)
    throw new Error('DB_URL set but neither DB_POLICIES_TABLE nor DB_TABLES given');

  async function refresh() {
    const policies = [];
    for (const { table, kind } of targets) {
      const [rows] = await pool.query(`SELECT * FROM ${ident(table)} LIMIT ?`, [Number(maxRows)]);
      const convert = kind === 'policies' ? policyFromRow : recordFromRow;
      rows.forEach((row, i) => {
        const p = convert(row, table, i);
        if (p) policies.push(p);
      });
    }
    onLoad(policies);
    return policies.length;
  }

  const n = await refresh();
  console.log(`db: loaded ${n} policies/records from ${targets.map((t) => t.table).join(', ')}`);
  const timer = setInterval(
    () => {
      refresh().catch((err) => console.error('db refresh failed:', err.message));
    },
    Math.max(5, refreshSeconds) * 1000,
  );
  timer.unref();

  return {
    refresh,
    close: () => {
      clearInterval(timer);
      return pool.end();
    },
  };
}
